id: P000133
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བྱང་ཆུབ་སེམས་དཔའི་སྡོམ་པའི་ཆོ་ག་དགེ་ལེགས་ཀྱི་ཆུ་རྒྱུན་ནོ། །
  authors:
  - མཛད་པ་པོ། བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  layers:
  - book_title
  - author
  - quotation
  id: IBA-SG-04-1
web_metadata:
  title:
    en: A Stream of Excellent Virtue:A Ritual for Bestowing the Bodhisattva Vow
    bo: བྱང་ཆུབ་སེམས་པའི་སྡོམ་པའི་ཆོ་ག་དགེ་ལེགས་ཀྱི་ཆུ་རྒྱུན།
  collection:
    en: IBA Sonam Gyaltsen Series–  Book 4
    bo: བསོོད་ནམས་རྒྱལ་མཚན་རྩོམ་བྲིས།–  དེབ། ༤
  author:
    en: Lama Dampa Sonam Gyaltsen
    bo: བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-SG-04-1
  category:
    en: Bodhichitta
    bo: བྱང་ཆུབ་ཀྱི་སེམས།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-SG-04-1.epub
  description:
    en: The text known by the title The Stream of Excellent Virtues is a liturgical
      exposition on generating the Engaging Bodhicitta.
    bo: འཇུག་པ་བྱང་སེམས་ཀྱི་སྡོམ་པ་རང་རྒྱུད་ལ་བསྐྱེད་བའི་རྒྱུ་ཏེ་ཆོ་གའི་རིམ་པ་གསལ་བར་བསྟན།
